# Generated by Django 3.2.25 on 2024-03-11 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ingredients'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredients',
            new_name='Ingredient',
        ),
    ]
